apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shigoto-client.fullname" . }}-vue
  labels:
    {{- include "shigoto-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shigoto-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shigoto-client.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
