apiVersion: apps/v1
kind: Deployment
metadata:
  name: shigoto-wss-go
  labels:
    component: wss-go
spec:
  replicas: 1
  selector:
    matchLabels:
      component: wss-go
  template:
    metadata:
      labels:
        component: wss-go
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: wss-go
          image: bogdanp3trovic/shigoto_production_result_service
          ports:
            - containerPort: 8080