replicaCount: 1

image:
  repository: bogdanp3trovic/shigoto_q_production_frontend
  pullPolicy: Always
  tag: 1.0.0

imagePullSecrets:
  - name: regcred

deployment:
  port: 3000



service:
  type: ClusterIP
  port: 80


resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

configmap:
  data:
    CELERY_FLOWER_PASSWORD: "debug"
    CELERY_FLOWER_USER: "debug"
    REDIS_URL: "redis://redis:6379/0"
    SENTRY_ENVIRONMENT: "local"
    USE_DOCKER: "yes"
    PYTHONUNBUFFERED: "0"
    DJANGO_SETTINGS_MODULE: "config.settings.production"
