apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-go
  labels:
    component: go
spec:
  replicas: 1
  selector:
    matchLabels:
      component: go
  template:
    metadata:
      labels:
        component: go
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: go
          image: bogdanp3trovic/shigoto_production_image_service
          ports:
            - containerPort: 5050