apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: shigoto-server
  namespace: shigoto
spec:
  project: defaykt

  source:
    repoURL: https://github.com/sgt-infrastructure
    targetRevision: HEAD
    path: shigoto-server
    directory:
      recurse: true

  destination: 
    server: https://kubernetes.default.svc
    namespace: shigoto

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true