apiVersion: apps/v1
kind: Deployment
metadata:
  name: shigoto-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:    
      containers:
      - name: redis
        image: redis:5.0.4
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"