apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: shigoto-q
  namespace: default
spec:
  dnsNames:
  - shigo.live
  - ws.shigo.live
  - api.shigo.live
  - image.shigo.live
  - grafana.shigo.live
  - influx.shigo.live
  secretName: shigoto-q-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
