apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: shigoto-q
  namespace: default
spec:
  dnsNames:
  - shigo.to
  - ws.shigo.to
  - api.shigo.to
  - grafana.shigo.to
  - influx.shigo.to
  secretName: shigoto-q-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
