apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  type: ClusterIP
  ports:
    - port: 8125
      protocol: TCP
      targetPort: 8125
  selector:
    app: telegraf
  sessionAffinity: None
