apiVersion: apps/v1
kind: Deployment
metadata:
  name: shigoto-celeryworker
  labels:
    component: celeryworker
spec:
  replicas: 1
  selector:
    matchLabels:
      component: celeryworker
  template:
    metadata:
      labels:
        component: celeryworker
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: celeryworker
          image: bogdanp3trovic/shigoto_q_production_celeryworker
          ports:
          - containerPort: 8000
          args:
            - /start-celeryworker
          volumeMounts:
          - name: cw-kubeconfig
            mountPath: /home/django/.kube
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: django-secret
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  key: WEBHOOK_SECRET
                  name: django-secret
            - name: LIVE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: LIVE_SECRET_KEY
                  name: django-secret
            - name: CELERY_FLOWER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_PASSWORD
                  name: django-configmap
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: SENTRY_DSN
                  name: django-secret
            - name: TEST_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: TEST_SECRET_KEY
                  name: django-secret
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: django-secret
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_HOST
                  name: django-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: django-secret
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PORT
                  name: django-secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: django-secret
            - name: CELERY_FLOWER_USER
              valueFrom:
                configMapKeyRef:
                  key: CELERY_FLOWER_USER
                  name: django-configmap
            - name: DOCKER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_SERVICE_URL
                  name: django-configmap
            - name: IPYTHONDIR
              valueFrom:
                configMapKeyRef:
                  key: IPYTHONDIR
                  name: django-configmap
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: django-configmap
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: SENTRY_ENVIRONMENT
                  name: django-configmap
            - name: USE_DOCKER
              valueFrom:
                configMapKeyRef:
                  key: USE_DOCKER
                  name: django-configmap
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SETTINGS_MODULE
                  name: django-configmap
      volumes:
      - name: cw-kubeconfig
        secret:
          secretName: kubeconfig
        
