apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shigoto-server.fullname" . }}-configmap
  labels:
    {{- include "shigoto-server.labels" . | nindent 4 }}
{{- with .Values.configmap.data }}
data:
  {{- toYaml . | nindent 4 }}
{{- end }}

